// <auto-generated>
// This file was generated by CKli v0.0.8--0277-dev.
// Do not edit this file manually. Changes will be lost when the file is regenerated.
//
// To regenerate: use 'ckli plugin info --compile-mode Debug' (or Release).
// To force recompilation without changing mode: use 'ckli plugin info --force'.
// Alternatively, delete this file and run 'ckli plugin info'.
// </auto-generated>

using CKli.Core;
using CK.Core;
using System;
using System.CodeDom.Compiler;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace CKli.Plugins;

[GeneratedCode("CKli", "0.0.8--0277-dev")]
public static class CompiledPlugins
{
    static ReadOnlySpan<byte> _configSignature => [0,74,72,145,119,115,45,169,236,231,54,249,57,193,38,29,54,97,233,162];

    public static IPluginFactory Get( PluginCollectorContext ctx )
    {
        return _configSignature.SequenceEqual( ctx.Signature ) ? UncheckedGet() : null;
    }

    public static IPluginFactory UncheckedGet()
    {
        var infos = new PluginInfo[]{
            new PluginInfo( "CKli.ShallowSolution.Plugin", "ShallowSolution", (PluginStatus)0, null, new IPluginTypeInfo[1] ),
            new PluginInfo( "CKli.BranchModel.Plugin", "BranchModel", (PluginStatus)0, null, new IPluginTypeInfo[1] ),
        };
        PluginInfo plugin;
        IPluginTypeInfo[] types;
        plugin = infos[0];
        types = (IPluginTypeInfo[])plugin.PluginTypes;
        types[0] = new PluginTypeInfo( plugin, "CKli.ShallowSolution.Plugin.ShallowSolutionPlugin", true, 0, 0 );
        plugin = infos[1];
        types = (IPluginTypeInfo[])plugin.PluginTypes;
        types[0] = new PluginTypeInfo( plugin, "CKli.BranchModel.Plugin.BranchModelPlugin", true, 0, 1 );
        var pluginCommands = new PluginCommand[]{
            new Cmd_checkout( infos[1].PluginTypes[0] ),
            new Cmd_commit( infos[1].PluginTypes[0] ),
        };
        var cmds = new Dictionary<string,Command>();
        foreach( var c in pluginCommands )
        {
            cmds.Add( c.CommandPath, c );
        }
        return new Generated( infos, pluginCommands, CommandNamespace.UnsafeCreate( cmds ) );
    }
}

[GeneratedCode("CKli", "0.0.8--0277-dev")]
sealed class Generated : IPluginFactory
{
    readonly PluginInfo[] _plugins;
    readonly PluginCommand[] _pluginCommands;
    readonly CommandNamespace _commands;

    internal Generated( PluginInfo[] plugins, PluginCommand[] pluginCommands, CommandNamespace commands )
    {
        _plugins = plugins;
        _pluginCommands = pluginCommands;
        _commands = commands;
    }
    
#if DEBUG
    public PluginCompileMode CompileMode => PluginCompileMode.Debug;
#else
    public PluginCompileMode CompileMode => PluginCompileMode.Release;
#endif

    public string GenerateCode() => throw new InvalidOperationException( "CompileMode is not PluginCompileMode.None" );

    public PluginCollection Create( IActivityMonitor monitor, World world )
    {
        var configs = world.DefinitionFile.ReadPluginsConfiguration( monitor );
        Throw.CheckState( "Plugins configurations have already been loaded.", configs != null );
        var objects = new object[2];
        objects[0] = new CKli.ShallowSolution.Plugin.ShallowSolutionPlugin( new PrimaryPluginContext( _plugins[0], configs, world ) );
        objects[1] = new CKli.BranchModel.Plugin.BranchModelPlugin( new PrimaryPluginContext( _plugins[1], configs, world ), (CKli.ShallowSolution.Plugin.ShallowSolutionPlugin)objects[0] );
        return PluginCollectionImpl.CreateAndBindCommands( objects, _plugins, _commands, _pluginCommands );
    }

    public void Dispose() { }
}
[GeneratedCode("CKli", "0.0.8--0277-dev")]
sealed class Cmd_checkout : PluginCommand
{
    internal Cmd_checkout( IPluginTypeInfo typeInfo )
        : base( typeInfo,
                "checkout",
                "Switch the working folder to the given branch.",
                1,
                -1,
                arguments: [
                    ("branchName", "Branch name to checkout."),
                ],
                options: [
                ],
                flags: [
                    (["--use-fallback",], "Don't create the branch if it doesn't exist, instead checks out the closest existing one." ),
                    (["--all",], "Consider all the Repos of the current World (even if current path is in a Repo)." ),
                ],
                "Checkout", MethodAsyncReturn.None ) {}
    protected override ValueTask<bool> HandleCommandAsync( IActivityMonitor monitor, CKliEnv context, CommandLineArguments cmdLine )
    {
        var a0 = cmdLine.EatArgument();
        var f0 = cmdLine.EatFlag( Flags[0].Names );
        var f1 = cmdLine.EatFlag( Flags[1].Names );
        if( !cmdLine.Close( monitor ) ) return ValueTask.FromResult( false );
        return ValueTask.FromResult( ((CKli.BranchModel.Plugin.BranchModelPlugin)Instance).Checkout(
                                           monitor, context, a0, f0, f1 ) );
    }
}
[GeneratedCode("CKli", "0.0.8--0277-dev")]
sealed class Cmd_commit : PluginCommand
{
    internal Cmd_commit( IPluginTypeInfo typeInfo )
        : base( typeInfo,
                "commit",
                "Commit any pending changes. Does nothing if there's no change to commit.",
                1,
                -1,
                arguments: [
                    ("message", "Required commit message."),
                ],
                options: [
                ],
                flags: [
                    (["--all",], "Consider all the Repos of the current World (even if current path is in a Repo)." ),
                ],
                "Commit", MethodAsyncReturn.None ) {}
    protected override ValueTask<bool> HandleCommandAsync( IActivityMonitor monitor, CKliEnv context, CommandLineArguments cmdLine )
    {
        var a0 = cmdLine.EatArgument();
        var f0 = cmdLine.EatFlag( Flags[0].Names );
        if( !cmdLine.Close( monitor ) ) return ValueTask.FromResult( false );
        return ValueTask.FromResult( ((CKli.BranchModel.Plugin.BranchModelPlugin)Instance).Commit(
                                           monitor, context, a0, f0 ) );
    }
}
